# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Fundament Software SPC <https://fundament.software>

[workspace]
members = [
  "feather-ui",
  "examples/basic-rs",
  "examples/basic-alc",
  "examples/paragraph-rs",
  "examples/graph-rs",
  "examples/calculator-rs",
  "examples/calculator-alc",
  "examples/list-rs",
  "feather-macro",
]
resolver = "2"
default-members = [
  "feather-ui",
  "examples/basic-alc",
  "examples/basic-rs",
  "examples/paragraph-rs",
  "examples/list-rs",
]

[workspace.package]
version = "0.1.5"
edition = "2021"
rust-version = "1.83.0"
license = "Apache-2.0"
homepage = "https://github.com/Fundament-Software/feathergui"
repository = "https://github.com/Fundament-Software/feathergui/"
readme = "README.md"

[workspace.dependencies]
im = "15.1"
wgpu = "25"
winit = "0.30"
eyre = "0.6"
ultraviolet = "0.9"
rand = { version = "0.8.5", features = ["std_rng"] }
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tracing = "0.1.40"
tokio = { version = "1.40", features = ["rt", "macros", "tracing", "signal"] }
feather-ui = { path = "feather-ui" }
alicorn = "0.1.2"
mlua = { version = "0.10", features = ["luajit52", "vendored"] }
glyphon = "0.9.0"
feather-macro = { version = "0.1", path = "feather-macro" }

[workspace.lints]
