version = 1
SPDX-PackageName = "Feather-UI"
SPDX-PackageSupplier = "Fundament Research Institute <https://fundament.institute>"
SPDX-PackageDownloadLocation = "https://github.com/Fundament-Software/feathergui"

[[annotations]]
path = "feather-ui/examples/calculator-rs/calculator-cs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Research Institute <https://fundament.institute>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "*.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Research Institute <https://fundament.institute>"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = ".envrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Research Institute <https://fundament.institute>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "*.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Research Institute <https://fundament.institute>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "*.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Research Institute <https://fundament.institute>"
SPDX-License-Identifier = "CC-BY-4.0"
