// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Fundament Research Institute <https://fundament.institute>

use crate::input::{MouseButton, MouseState, RawEvent};
use crate::layout::leaf;
use crate::reactive::{self, DeferProvider, Signal, SignalProvider};
use crate::{AbsPoint, AbsVector, PxPoint, PxRect, RelDim, UnResolve, event, layout};
use core::f32;
use enum_variant_type::EnumVariantType;
use feather_macro::Dispatch;
use smallvec::{SmallVec, smallvec};
use std::collections::HashMap;
use std::rc::Rc;
use std::sync::Arc;
use winit::event::DeviceId;
use winit::keyboard::NamedKey;

/// Represents processed mouse events, transformed into more useful
/// [`MouseAreaEvent::OnClick`], [`MouseAreaEvent::OnDrag`],
/// [`MouseAreaEvent::Hover`], etc. Generated by [`MouseArea`].
#[derive(Debug, Dispatch, EnumVariantType, Clone, PartialEq)]
#[evt(derive(Clone), module = "mouse_area_event")]
pub enum MouseAreaEvent {
    OnClick(MouseButton, AbsPoint),
    OnDblClick(MouseButton, AbsPoint),
    OnDrag(MouseButton, AbsVector),
}

#[derive(Default, Debug, Copy, Clone, PartialEq, Eq)]
#[repr(u8)]
pub enum MouseAreaState {
    #[default]
    Default,
    Hover,
    Active,
    Drag,
}

#[derive(Default, Clone, PartialEq)]
struct MouseAreaInternal {
    lastdown: HashMap<(DeviceId, u64), (PxPoint, bool)>,
    hover: bool,
    deadzone: f32,
    state: MouseAreaState,
}

impl MouseAreaInternal {
    fn hover_state(buttons: u16, hover: bool) -> MouseAreaState {
        let active = (buttons & MouseButton::Left as u16) != 0;
        match (active, hover) {
            (true, true) => MouseAreaState::Active,
            (true, false) => MouseAreaState::Hover,
            (false, true) => MouseAreaState::Hover,
            (false, false) => MouseAreaState::Default,
        }
    }
}

impl event::StateMachine<RawEvent, (PxRect, RelDim), MouseAreaEvent, MouseAreaState>
    for MouseAreaInternal
{
    fn update(
        &mut self,
        event: RawEvent,
        input: &(PxRect, RelDim),
    ) -> (impl IntoIterator<Item = MouseAreaEvent>, event::EventRes) {
        let (area, dpi) = input;

        match event {
            RawEvent::Key {
                down,
                logical_key: winit::keyboard::Key::Named(code),
                ..
            } => {
                if (code == NamedKey::Enter || code == NamedKey::Accept) && down {
                    (
                        smallvec![MouseAreaEvent::OnClick(
                            crate::input::MouseButton::Left,
                            AbsPoint::zero(),
                        )],
                        event::CONSUME,
                    )
                } else {
                    (smallvec![], event::CONSUME)
                }
            }
            RawEvent::MouseOn { all_buttons, .. } | RawEvent::MouseOff { all_buttons, .. } => {
                self.hover = matches!(event, RawEvent::MouseOff { .. });
                self.state = Self::hover_state(all_buttons, self.hover);
                (smallvec![], event::CONSUME)
            }
            RawEvent::MouseMove {
                device_id,
                pos,
                all_buttons,
                ..
            } => {
                self.state = Self::hover_state(all_buttons, self.hover);
                for i in 0..5 {
                    let deadzone = self.deadzone;
                    if let Some((last_pos, drag)) = self.lastdown.get_mut(&(device_id, (1 << i))) {
                        let diff = pos - *last_pos;
                        if !*drag && diff.dot(diff) > deadzone {
                            *drag = true;
                        }

                        let b = match i {
                            0 => MouseButton::Left,
                            1 => MouseButton::Middle,
                            2 => MouseButton::Right,
                            3 => MouseButton::Back,
                            4 => MouseButton::Forward,
                            _ => panic!("Impossible number"),
                        };
                        if *drag {
                            *last_pos = pos;
                            return (
                                smallvec![MouseAreaEvent::OnDrag(b, diff.unresolve(*dpi))],
                                event::CONSUME,
                            );
                        }
                    }
                }

                (smallvec![], event::CONSUME)
            }
            RawEvent::Mouse {
                device_id,
                state,
                pos,
                button,
                ..
            } => {
                self.state = Self::hover_state(button as u16, self.hover);
                match state {
                    MouseState::Down => {
                        if area.contains(pos) {
                            self.lastdown
                                .insert((device_id, button as u64), (pos, false));
                        }
                        (smallvec![], event::CONSUME)
                    }
                    MouseState::Up => {
                        if let Some((last_pos, drag)) =
                            self.lastdown.remove(&(device_id, button as u64))
                            && area.contains(pos)
                        {
                            (
                                smallvec![if drag {
                                    let diff = pos - last_pos;
                                    MouseAreaEvent::OnDrag(button, diff.unresolve(*dpi))
                                } else {
                                    MouseAreaEvent::OnClick(button, pos.unresolve(*dpi))
                                }],
                                event::CONSUME,
                            )
                        } else {
                            (smallvec![], event::CONSUME)
                        }
                    }
                    MouseState::DblClick => {
                        if let Some((last_pos, drag)) =
                            self.lastdown.remove(&(device_id, button as u64))
                            && area.contains(pos)
                        {
                            let evts: SmallVec<[_; 1]> = if drag {
                                smallvec![
                                    MouseAreaEvent::OnClick(button, pos.unresolve(*dpi)),
                                    MouseAreaEvent::OnDblClick(button, pos.unresolve(*dpi)),
                                ]
                            } else {
                                smallvec![if drag {
                                    let diff = pos - last_pos;
                                    MouseAreaEvent::OnDrag(button, diff.unresolve(*dpi))
                                } else {
                                    MouseAreaEvent::OnClick(button, pos.unresolve(*dpi))
                                },]
                            };
                            (evts, event::CONSUME)
                        } else {
                            (smallvec![], event::CONSUME)
                        }
                    }
                }
            }
            RawEvent::Touch {
                device_id,
                index,
                state,
                pos,
                ..
            } => match state {
                crate::input::TouchState::Start => {
                    self.state = Self::hover_state(MouseButton::Left as u16, self.hover);
                    if area.contains(pos.xy()) {
                        self.lastdown
                            .insert((device_id, index as u64), (pos.xy(), false));
                    }
                    (smallvec![], event::CONSUME)
                }
                crate::input::TouchState::Move => {
                    let deadzone = self.deadzone;
                    self.state = Self::hover_state(MouseButton::Left as u16, self.hover);
                    if let Some((last_pos, drag)) =
                        self.lastdown.get_mut(&(device_id, index as u64))
                    {
                        let diff = pos.xy() - *last_pos;
                        if !*drag && diff.dot(diff) > deadzone {
                            *drag = true;
                        }
                        if *drag {
                            return (
                                smallvec![MouseAreaEvent::OnDrag(
                                    MouseButton::Left,
                                    diff.unresolve(*dpi)
                                )],
                                event::CONSUME,
                            );
                        }
                    }
                    (smallvec![], event::CONSUME)
                }
                crate::input::TouchState::End => {
                    self.state = Self::hover_state(0, self.hover);
                    if let Some((last_pos, drag)) = self.lastdown.remove(&(device_id, index as u64))
                        && area.contains(pos.xy())
                    {
                        let diff = pos.xy() - last_pos;
                        (
                            smallvec![if drag {
                                MouseAreaEvent::OnDrag(MouseButton::Left, diff.unresolve(*dpi))
                            } else {
                                MouseAreaEvent::OnClick(MouseButton::Left, pos.xy().unresolve(*dpi))
                            }],
                            event::CONSUME,
                        )
                    } else {
                        (smallvec![], event::CONSUME)
                    }
                }
            },
            _ => (smallvec![], event::FORWARD),
        }
    }

    fn get(&self, _: &(PxRect, RelDim)) -> MouseAreaState {
        self.state
    }
}
/*
            input_mask: RawEventKind::Mouse as u64
                | RawEventKind::MouseMove as u64
                | RawEventKind::Touch as u64
                | RawEventKind::Key as u64,
} */

pub struct MouseArea<T, P1: SignalProvider<Item = f32> + ?Sized> {
    props: Rc<T>,
    deadzone: Signal<P1>, // A deadzone of infinity disables drag events
    machine: crate::layout::DeferMachine<<dyn leaf::Prop as crate::layout::Desc>::Provider>,
}

impl<'a, T: leaf::Prop, P1: SignalProvider<Item = f32> + ?Sized> MouseArea<T, P1> {
    pub fn new(
        props: T,
        deadzone: Signal<P1>,
    ) -> (
        Self,
        impl event::EventStream<'static, MouseAreaEvent>,
        Signal<impl SignalProvider<Item = MouseAreaState>>,
    ) {
        let (bounce, anti) = event::BounceStream::new();

        let state: Signal<DeferProvider<dyn SignalProvider<Item = (PxRect, RelDim)>>> =
            reactive::defer();

        let (stream, output) =
            event::statemachine(MouseAreaInternal::default(), bounce, state.clone());
        (
            Self {
                props: props.into(),
                deadzone: deadzone,
                machine: (anti, state),
            },
            stream,
            output,
        )
    }
}

impl<'l, T: leaf::Prop + 'static, P1: SignalProvider<Item = f32> + ?Sized> super::Component
    for MouseArea<T, P1>
where
    for<'a> &'a T: Into<&'a (dyn leaf::Prop + 'static)>,
{
    type Props = T;
    type R = layout::Node<T, dyn leaf::Prop, ()>;

    fn layout(
        &self,
        _: &Arc<crate::graphics::Driver>,
        _: reactive::MutableSignal<crate::RelDim>,
    ) -> Self::R {
        layout::Node::<T, dyn leaf::Prop, ()> {
            props: self.props.clone(),
            children: reactive::empty_signal().into_dyn_signal(),
            renderable: None,
            machine: Some(self.machine.clone()),
        }
    }
}
