# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Fundament Research Institute <https://fundament.institute>

syntax = "LuaJIT"
call_parentheses = "NoSingleTable"
collapse_simple_statement = "Always"
